plugins {
  id 'org.cadixdev.licenser' version '0.6.1' apply false
}

defaultTasks 'build', 'checkLicenses', 'shadowJar'

allprojects {
    group "dev.ein.cloudnet.module.management-socket"
    version = "1.1-RELEASE"

    repositories {
        mavenCentral()
        maven { url = 'https://oss.sonatype.org/content/repositories/snapshots/' }
    }

    project.ext {
      dependencyVersionCloudNet = ''
      dependencyVersionLombok = '1.18.36'
      dependencyVersionJunixSocket = '2.8.3'
      dependencyVersionJline = '3.28.0'
      cliFile = 'cloudnet-client.jar'
    }
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'org.cadixdev.licenser'

    compileJava {
        options.encoding = 'UTF-8'
    }

    sourceCompatibility = 1.23
    targetCompatibility = 1.23

    dependencies {
      implementation(platform('eu.cloudnetservice.cloudnet:bom:4.0.0-RC11.2'))
      annotationProcessor(platform('eu.cloudnetservice.cloudnet:bom:4.0.0-RC11.2'))
      compileOnly("""org.projectlombok:lombok:${dependencyVersionLombok}""")
      annotationProcessor("""org.projectlombok:lombok:${dependencyVersionLombok}""")
      implementation("""com.kohlschutter.junixsocket:junixsocket-core:${dependencyVersionJunixSocket}""")
      compileOnly('org.slf4j:slf4j-api:2.0.16')
      compileOnly('eu.cloudnetservice.cloudnet:platform-inject-api')
      annotationProcessor('eu.cloudnetservice.cloudnet:platform-inject-processor')
    }

    license {
      include '**/*.java'
      header = project.rootProject.file('LICENSE_HEADER')
    }
}
