---
name: Build the plugin
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    needs: [ install-dependencies ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Package jars
        run: ./gradlew shadowJar

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-artifacts
          path: |
            cli/build/*.jar
            module/build/*.jar